# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliach_rating', '0002_auto_20160518_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='sluchim',
            name='name',
            field=models.CharField(default='bob', max_length=100),
        ),
        migrations.AddField(
            model_name='sluchim',
            name='phone',
            field=models.IntegerField(default=99999999999),
        ),
    ]
