# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sliach_rating', '0004_auto_20160519_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('rate', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='sluchim',
            name='picture',
            field=models.ImageField(default='./nick_XBVHPAg.jpg ', upload_to=''),
        ),
        migrations.AddField(
            model_name='rate',
            name='sliach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sliach_rating.Sluchim'),
        ),
    ]
